/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music;

import javax.swing.JOptionPane;


/**
 *
 * @author dongyiyoo
 */
public class PlaylistGUI extends javax.swing.JFrame {

    
    StackInterface stackInterface;
    LinearListInterface dllInterface;
    private DLList popList = new DLList();
    private DLList rockList = new DLList();
   
    public PlaylistGUI() {
        dllInterface = new DLList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBtn = new javax.swing.JButton();
        likedBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        searchTf = new javax.swing.JTextField();
        popPan = new javax.swing.JPanel();
        popaddBtn = new javax.swing.JButton();
        popdeleteBtn = new javax.swing.JButton();
        popmoveBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        popTa = new javax.swing.JTextArea();
        popplayBtn = new javax.swing.JButton();
        nosBtn = new javax.swing.JButton();
        rockPan = new javax.swing.JPanel();
        rockaddBtn = new javax.swing.JButton();
        rockdeleteBtn = new javax.swing.JButton();
        rockmoveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rockTa = new javax.swing.JTextArea();
        rockplayBtn = new javax.swing.JButton();
        nosBtn2 = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainBtn.setText("Main");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, -1, -1));

        likedBtn.setText("Liked Songs");
        likedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedBtnActionPerformed(evt);
            }
        });
        getContentPane().add(likedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        getContentPane().add(searchTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, -1));

        popPan.setBackground(new java.awt.Color(230, 230, 254));
        popPan.setBorder(javax.swing.BorderFactory.createTitledBorder("POP"));

        popaddBtn.setText("Add");
        popaddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popaddBtnActionPerformed(evt);
            }
        });

        popdeleteBtn.setText("Delete");
        popdeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popdeleteBtnActionPerformed(evt);
            }
        });

        popmoveBtn.setText("Move");
        popmoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popmoveBtnActionPerformed(evt);
            }
        });

        popTa.setColumns(20);
        popTa.setRows(5);
        jScrollPane2.setViewportView(popTa);

        popplayBtn.setText("Play");

        nosBtn.setText("Num of songs");
        nosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popPanLayout = new javax.swing.GroupLayout(popPan);
        popPan.setLayout(popPanLayout);
        popPanLayout.setHorizontalGroup(
            popPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(popaddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(popdeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(popmoveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(popplayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        popPanLayout.setVerticalGroup(
            popPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(popPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popPanLayout.createSequentialGroup()
                        .addComponent(popaddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(popdeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(popmoveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(popplayBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nosBtn)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(popPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 370, 200));

        rockPan.setBackground(new java.awt.Color(230, 230, 254));
        rockPan.setBorder(javax.swing.BorderFactory.createTitledBorder("ROCK"));

        rockaddBtn.setText("Add");
        rockaddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockaddBtnActionPerformed(evt);
            }
        });

        rockdeleteBtn.setText("Delete");
        rockdeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockdeleteBtnActionPerformed(evt);
            }
        });

        rockmoveBtn.setText("Move");

        rockTa.setColumns(20);
        rockTa.setRows(5);
        jScrollPane1.setViewportView(rockTa);

        rockplayBtn.setText("Play");

        nosBtn2.setText("Num of songs");
        nosBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nosBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rockPanLayout = new javax.swing.GroupLayout(rockPan);
        rockPan.setLayout(rockPanLayout);
        rockPanLayout.setHorizontalGroup(
            rockPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rockPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rockaddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rockdeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rockmoveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rockplayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nosBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        rockPanLayout.setVerticalGroup(
            rockPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rockPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rockPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(rockPanLayout.createSequentialGroup()
                        .addComponent(rockaddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rockdeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rockmoveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rockplayBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nosBtn2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(rockPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 370, 200));

        titleLbl.setFont(new java.awt.Font("Noto Sans Myanmar", 1, 30)); // NOI18N
        titleLbl.setText("My Playlist");
        getContentPane().add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        bgLbl.setBackground(new java.awt.Color(255, 255, 255));
        bgLbl.setOpaque(true);
        getContentPane().add(bgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void likedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likedBtnActionPerformed
        // TODO add your handling code here:
        LikedSongGUI myGUI = new LikedSongGUI();
        myGUI.setVisible(true); // make the new ui appear
        
        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_likedBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        MainGUI myGUI = new MainGUI();
        myGUI.setVisible(true); // make the new ui appear
        
        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_mainBtnActionPerformed

    private void popdeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popdeleteBtnActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_popdeleteBtnActionPerformed

    private void popaddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popaddBtnActionPerformed
        // TODO add your handling code here:
      
        // Check if popStack is empty
    if (!LikedSongGUI.popStack.isEmpty()) {
        // Retrieve the latest song title categorized under the pop genre from popStack
        String title = (String) LikedSongGUI.popStack.peek();
        // Add the last song title with rock genre to the popTa
        popTa.append(title + "\n");
        // Delete the last song in popStack
        LikedSongGUI.popStack.pop();
    } else {
        // Display a message when popStack is empty
        JOptionPane.showMessageDialog(this, "No POP songs in the liked list anymore.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
        
        
    }//GEN-LAST:event_popaddBtnActionPerformed

    private void rockaddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockaddBtnActionPerformed
        // TODO add your handling code here:

    // Check if rockStack is empty
    if (!LikedSongGUI.rockStack.isEmpty()) {
        // Retrieve the latest song title categorized under the rock genre from rockStack
        String title = (String) LikedSongGUI.rockStack.peek();
        // Add the last song title with rock genre to the rockTa
        rockTa.append(title + "\n");
        // Delete the last song in rockStack
        LikedSongGUI.rockStack.pop();
    } else {
        // Display a message when rockStack is empty
        JOptionPane.showMessageDialog(this, "No ROCK songs in the liked list anymore.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_rockaddBtnActionPerformed

    private void nosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nosBtnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nosBtnActionPerformed

    private void nosBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nosBtn2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nosBtn2ActionPerformed

    private void rockdeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockdeleteBtnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_rockdeleteBtnActionPerformed

    private void popmoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popmoveBtnActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_popmoveBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton likedBtn;
    private javax.swing.JButton mainBtn;
    private javax.swing.JButton nosBtn;
    private javax.swing.JButton nosBtn2;
    private javax.swing.JPanel popPan;
    private javax.swing.JTextArea popTa;
    private javax.swing.JButton popaddBtn;
    private javax.swing.JButton popdeleteBtn;
    private javax.swing.JButton popmoveBtn;
    private javax.swing.JButton popplayBtn;
    private javax.swing.JPanel rockPan;
    private javax.swing.JTextArea rockTa;
    private javax.swing.JButton rockaddBtn;
    private javax.swing.JButton rockdeleteBtn;
    private javax.swing.JButton rockmoveBtn;
    private javax.swing.JButton rockplayBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables

}
