/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music;

import javax.swing.JOptionPane;

/**
 *
 * @author dongyiyoo
 */
public class LikedSongGUI extends javax.swing.JFrame {
    
    public static StackInterface popStack = new MyStack();
    public static StackInterface rockStack = new MyStack();
    
    public LikedSongGUI() {
        popStack = new MyStack();
        rockStack = new MyStack();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        playBtn = new javax.swing.JButton();
        mainBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        addPan = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        songTf = new javax.swing.JTextField();
        genreCb = new javax.swing.JComboBox<>();
        searchBtn = new javax.swing.JButton();
        likedPan = new javax.swing.JPanel();
        listBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTa = new javax.swing.JTextArea();
        nosBtn = new javax.swing.JButton();
        bgLbl = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playBtn.setText("My Playlist");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });
        getContentPane().add(playBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        mainBtn.setText("Main Page");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        titleLbl.setFont(new java.awt.Font("Noto Sans Myanmar", 1, 30)); // NOI18N
        titleLbl.setText("Liked Music");
        getContentPane().add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        addPan.setBackground(new java.awt.Color(230, 230, 254));
        addPan.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Music"));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        genreCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POP", "ROCK", " " }));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanLayout = new javax.swing.GroupLayout(addPan);
        addPan.setLayout(addPanLayout);
        addPanLayout.setHorizontalGroup(
            addPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(addPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(songTf)
                    .addComponent(genreCb, 0, 207, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(addPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17))
        );
        addPanLayout.setVerticalGroup(
            addPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(addPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(songTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreCb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(addPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 370, 140));

        likedPan.setBackground(new java.awt.Color(230, 230, 254));
        likedPan.setBorder(javax.swing.BorderFactory.createTitledBorder("Liked"));

        listBtn.setText("List");
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        listTa.setColumns(20);
        listTa.setRows(5);
        jScrollPane1.setViewportView(listTa);

        nosBtn.setText("Number of songs");
        nosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout likedPanLayout = new javax.swing.GroupLayout(likedPan);
        likedPan.setLayout(likedPanLayout);
        likedPanLayout.setHorizontalGroup(
            likedPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likedPanLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(likedPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, likedPanLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(likedPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(removeBtn)
                            .addComponent(listBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, likedPanLayout.createSequentialGroup()
                        .addComponent(nosBtn)
                        .addContainerGap())))
        );
        likedPanLayout.setVerticalGroup(
            likedPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likedPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(likedPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(likedPanLayout.createSequentialGroup()
                        .addComponent(listBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nosBtn)
                .addContainerGap())
        );

        getContentPane().add(likedPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, 270));

        bgLbl.setBackground(new java.awt.Color(255, 255, 255));
        bgLbl.setOpaque(true);
        getContentPane().add(bgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 430, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        // TODO add your handling code here:
        PlaylistGUI myGUI = new PlaylistGUI();
        myGUI.setVisible(true); // make the new ui appear
        
        
    }//GEN-LAST:event_playBtnActionPerformed

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        MainGUI myGUI = new MainGUI();
        myGUI.setVisible(true); 
        
        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_mainBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        if (songTf.getText().isEmpty()) {
            // Show an error message 
            JOptionPane.showMessageDialog(null, "Please enter the title of the song you wish to add.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        String song = songTf.getText();           
        String genre = (String) genreCb.getSelectedItem();
        
        //Add songs into each stacks
            if (genre.equals("POP")) {
            popStack.push(song);
        } else if (genre.equals("ROCK")) {
            rockStack.push(song);
        }

        //Display added songs
        listTa.append(song + ", genre:" + genre+"\n");
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        
        // Display a message when the stack is empty
        if (popStack.isEmpty() && rockStack.isEmpty()) {
        listTa.append("There are no songs to be removed!\n");
    } else {
        // Remove rock songs after removing all pop songs
        String removedSong = null;
        if (!popStack.isEmpty()) {
            removedSong = (String) popStack.pop();
        } else if (!rockStack.isEmpty()) {
            removedSong = (String) rockStack.pop();
        }
        if (removedSong != null) {
            listTa.append(removedSong + " was removed from the list.\n");
        }
    }
        
    }//GEN-LAST:event_removeBtnActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
   
     // Display popsong list
    listTa.append(popStack.displayStack1() + "\n");
    
    // Display rocksong list
    listTa.append(rockStack.displayStack2() + "\n");


    }//GEN-LAST:event_listBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
       
        String song = songTf.getText();           
        String genre = (String) genreCb.getSelectedItem();

        // Initialize a variable to hold search results
        String result = "The song is not found in the playlist.";

        // Search songs in the appropriate stack based on the selected genre
        if (genre.equals("POP")) {
            // Search for songs in the pop genre
            result = popStack.search(song);
        } else if (genre.equals("ROCK")) {
            //  Search for songs in the rock genre
            result = rockStack.search(song);
        }

        // Display the result on the text area
        listTa.append(result + "\n"); 
 
    }//GEN-LAST:event_searchBtnActionPerformed

    private void nosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nosBtnActionPerformed
        // TODO add your handling code here:
 
        // Get the number of songs in the pop, rock stack
        int numOfPopSongs = popStack.size();
        int numOfRockSongs = rockStack.size();
        int totalNumOfSongs = numOfPopSongs + numOfRockSongs;
        
        //Display the total num of songs
        listTa.append("There are " + totalNumOfSongs + " songs in the liked list.\n");
        
    }//GEN-LAST:event_nosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LikedSongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LikedSongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LikedSongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LikedSongGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LikedSongGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addPan;
    private javax.swing.JLabel bgLbl;
    private javax.swing.JComboBox<String> genreCb;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel likedPan;
    private javax.swing.JButton listBtn;
    private javax.swing.JTextArea listTa;
    private javax.swing.JButton mainBtn;
    private javax.swing.JButton nosBtn;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField songTf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}