/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package music;

/**
 * 13/03/24
 * @author dongyiyoo
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        likeBtn = new javax.swing.JButton();
        PlaylistBtn = new javax.swing.JButton();
        imgLbl = new javax.swing.JLabel();
        LikedsongLbl = new javax.swing.JLabel();
        MylibLbl = new javax.swing.JLabel();
        bgLbl = new javax.swing.JLabel();
        playbgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(430, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        likeBtn.setText(">>");
        likeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        likeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(likeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 50, 20));

        PlaylistBtn.setText(">>");
        PlaylistBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaylistBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PlaylistBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 353, 50, 20));

        imgLbl.setIcon(new javax.swing.ImageIcon("/Users/dongyiyoo/Desktop/NCI Year 2/Data Structures and Algorithms/CA2/Music/img/cat.png")); // NOI18N
        imgLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 231, 229), 3, true));
        getContentPane().add(imgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 330, 270));

        LikedsongLbl.setFont(new java.awt.Font("Noto Sans Kannada", 0, 13)); // NOI18N
        LikedsongLbl.setText("Liked Song");
        getContentPane().add(LikedsongLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, 30));

        MylibLbl.setFont(new java.awt.Font("Noto Sans Kannada", 1, 18)); // NOI18N
        MylibLbl.setText("My Library");
        getContentPane().add(MylibLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 140, 30));

        bgLbl.setBackground(new java.awt.Color(255, 255, 255));
        bgLbl.setOpaque(true);
        getContentPane().add(bgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 370));

        playbgLbl.setIcon(new javax.swing.ImageIcon("/Users/dongyiyoo/Desktop/NCI Year 2/Data Structures and Algorithms/CA2/Music/img/music player.png")); // NOI18N
        getContentPane().add(playbgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void likeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeBtnActionPerformed
        // TODO add your handling code here:
        LikedSongGUI myGUI = new LikedSongGUI();
        myGUI.setVisible(true); // make the new ui appear
        
        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_likeBtnActionPerformed

    private void PlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaylistBtnActionPerformed
        // TODO add your handling code here:
        PlaylistGUI myGUI = new PlaylistGUI();
        myGUI.setVisible(true); // make the new ui appear
        
        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_PlaylistBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LikedsongLbl;
    private javax.swing.JLabel MylibLbl;
    private javax.swing.JButton PlaylistBtn;
    private javax.swing.JLabel bgLbl;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JButton likeBtn;
    private javax.swing.JLabel playbgLbl;
    // End of variables declaration//GEN-END:variables
}
